### ISSUE TITLE
Support instantiateWithCode calls

### ISSUE THREAD

**Issue by kwingram25** [paritytech/canvas-ui#71]
Substrate and Canvas Node are moving from contracts.putCode -> contracts.instantiate to instantiateWithCode (single step). The UI must support both types of instantiation.

**Comment by Robbepop** [comment]
Users who have transitioned successfully to ink! 3.0-rc3 are currently experiencing incompatibility issues due to this. I put it on high-priority list and we should stop development of new features until this has been resolved. The problem is that this kind of requires some UI changes as well since we no longer have a 3-way smart contract setup with `put_code`, `instantiate` and `call` but merely 2 way set-up with different entry points:
1. `instantiate_new` -> `call`
2. `instantiate_from_code` -> `call`
Both `instantiate_new` and `instantiate_from_code` require UI adjustments.
@erler please think about some proper design. Imo we should keep this as simple as possible for now in order to get support for the new instantiation methods out as quickly as possible and later refine them.

**Comment by kwingram25** [comment]
Have a temporary fix nearly ready to merge but agree that a better designed solution is needed. With the temporary fix the app entry point changes depending on what API is supported ("Upload" or "Deploy/Instantiate")

**Comment by kwingram25** [comment]
Closed for now by #75
