### ISSUE TITLE
Error when executing RPC call `delegator::get()`

### ISSUE THREAD

**Issue by cmichi** [paritytech/canvas-ui#95]
After having deployed our `delegator` example I'm unable to execute the RPC transaction `get() : i32`:

![ui](https://user-images.githubusercontent.com/241530/114858434-bdab6800-9de9-11eb-9970-f40f68ac1a34.jpg)

The return value should be `i32`, but it's the unit type `()`. There is no network traffic visible in the browsers web dev tools, hence I assume it's an error which happens already in the UI.

## How to reproduce

I've attached all necessary files [here](https://github.com/paritytech/canvas-ui/files/6317639/reproduce-95.zip).

* First deploy `adder`, `accumulator` and `subber`
* Then deploy `delegator` (with endowment `1000000`) while providing the hashes of those sub-contracts:
  * accumulator_hash: 0x694f690cebfca6ada3e548747b9e9438f4a277c77e8dc66bbdbfc441d921b3c7
  * adder_hash: 0x74de7cebd87ffc53621987d0ec18f610867dfd22b56ee8f7162e3a7bbef99bd4
  * subber_hash: 0x27b8eebfe9e80ae0d90f7f7b60f4acfe530b7f1025e5b462e49719757a88f0d4

**Comment by achimcc** [comment]
- First, `canvas-ui` failed to display meaningful error messages, this was implmented by https://github.com/paritytech/canvas-ui/pull/99
- The correct evaluation of the error messages revealed that the gas estimation was wrong. We traced this back to substrate in https://github.com/paritytech/substrate/issues/8693
- Which was finally fixed by: https://github.com/paritytech/substrate/pull/8976, which closes the issue.
